server:
  port: 8080

spring:
  application:
    name: movie-library

  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:movie_library}
    username: ${DB_USERNAME:root} // reminder that these are windows env variables
    password: ${DB_PASSWORD:root} // because i forgot to add them :p
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
